pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/TapabrataSikder/wipro_selenium_java_Apr_2026.git'
            }
        }
        stage('Docker Build & Run') {
            steps {
                // Navigate into the subfolder where your Dockerfile is located
                dir('ParabankAutomation') {
                    bat 'docker build -t parabank-automation .'
                    bat 'docker run --rm parabank-automation'
                }
            }
        }
    }
}